govuk-one-login/ipv-cri-uk-passport-front-v1

.github/workflows/secure-post-merge.yml
Enabling temporarily while testing the pipeline, to be removed later
Issue: PLAT-788
Co-authored-by:
=> On workflow_dispatch to easily trigger run

deploy/template.yaml
=> Replace hardcoded accountids with Environment param

.gitignore, deploy/template.yaml
Import Private APIGW Base url from Api stack
Use Vpc stack provided SG group, Cidr range
=> PLAT-789 - deploying to new passport build account

src/locales/cy/default.yml, src/locales/cy/fields.yml, src/locales/en/default.yml, src/views/passport/details.html
Bug fixes for welsh translation of RetryBanner and validation messages
=> LIME-669 - Welsh validation and retryBannerTitle  msg bug fixes

src/views/passport/details.html
- Corrected element ID.
- [LIME-677](https://govukverify.atlassian.net/browse/LIME-677)
[LIME-677]: https://govukverify.atlassian.net/browse/LIME-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-677 - Corrected element ID called upon.

src/views/passport/details.html
- Added `{{super ()}}` to accommodate CSP script.
- [LIME-677](https://govukverify.atlassian.net/browse/LIME-677)
https://github.com/alphagov/di-ipv-cri-uk-passport-front-v1/assets/107932230/e57e7db5-f203-44e6-bba6-26757b0fc88b
[LIME-677]: https://govukverify.atlassian.net/browse/LIME-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-677 - Added `{{super ()}}` to accommodate CSP script.

deploy/template.yaml
Added conditionals so service is only scaled in build and prod as expected
To allow accurate performance testing in build
=> LIME-698: Right sizing passport front

deploy/template.yaml
Aligned access log bucket with dev platform
Attempting to fix permissions for passport front logs
=> LIME-741: Aligned bucket permissions with dev platform sam app

README.md
Updated Readme
Readme was missing deployment information for new environments and yarn tasks.
- [LIME-742](https://govukverify.atlassian.net/browse/LIME-742)
[LIME-742]: https://govukverify.atlassian.net/browse/LIME-742?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-742 Update Readme

.github/workflows/post-merge-deploy-to-dev.yml
Enable deploy to dev from workflow.
To allow testing in the dev environment via dev env pipeline deployment.
- [LIME-783](https://govukverify.atlassian.net/browse/LIME-783)
[LIME-783]: https://govukverify.atlassian.net/browse/LIME-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-783 Allow deploy to dev from workflow

src/app/passport/fields.js, src/app/passport/fieldsHelper.js, src/app/passport/fieldsHelper.test.js, src/locales/cy/fields.yml, src/locales/en/fields.yml
Added custom field validator for expiryDate.
Current expiry date validation is not operating correctly.
- [LIME-783](https://govukverify.atlassian.net/browse/LIME-783)
[LIME-783]: https://govukverify.atlassian.net/browse/LIME-783?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-783 Add custom field validator for expiryDate

src/locales/cy/default.yml, src/locales/en/default.yml
=> LIME-807 - cookie banner updates

.github/workflows/pre-merge-checks.yml
BAU Sonarcloud run on main
modified:   .github/workflows/pre-merge-checks.yml
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXX)
=> BAU Sonarcloud run on main

sonar-project.properties
IPS-310 Sonarcloud Integration to govuk-one-login
IPS-310 Sonarcloud Integration to govuk-one-login
- [IPS-310](https://govukverify.atlassian.net/browse/IPS-310)
[IPS-310]: https://govukverify.atlassian.net/browse/IPS-310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-310 Sonarcloud Integration to govuk-one-login

.github/workflows/pre-merge-checks.yml, package.json, sonar-project.properties, test/browser/features/passport/Passport.feature
Added exclusions to match coverage report
So that sonar and frontend test coverage are reporting on the same metrics
=> LIME-819: Updating test exclusions in sonar

src/locales/en/default.yml, test/browser/features/passport/Passport.feature, test/browser/pages/PassportPage.js, test/browser/pages/error.js, test/browser/step_definitions/PassportStepDefs.js, test/browser/step_definitions/errors.js
added tests to check url for support page
added tests to check bata banner
=> LIME - 834

deploy/template.yaml
Align task scaling with DLFront/CoreFront/AddressFront configurations.
Align PassportFront with DL Front values
- [LIME-727](https://govukverify.atlassian.net/browse/LIME-727)
[LIME-727]: https://govukverify.atlassian.net/browse/LIME-727?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-727 Align task scaling with DL-front

.github/dependabot.yml, .github/workflows/checkov.yml, .github/workflows/codeql.yml, .github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/pre-merge-checks.yml, .github/workflows/secure-post-merge.yml
Updates to remove most of the githib action deprecation warnings and updates in preparation for canary deployments rollout
workflows and dependabot changes:
* remove deprecations
* implement dev-platform actions
* add dependabot for workflow actions
Updates to remove most of the githib action deprecation warnings and updates in preparation for canary deployments rollout
- [IPS-477](https://govukverify.atlassian.net/browse/IPS-477)
- [IPS-494](https://govukverify.atlassian.net/browse/IPS-494)
[IPS-477]: https://govukverify.atlassian.net/browse/IPS-477?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-494]: https://govukverify.atlassian.net/browse/IPS-494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1ci …
=> IPS-477 fix workflow warnings

src/locales/cy/default.yml, src/locales/en/default.yml, test/browser/pages/PassportPage.js, test/browser/step_definitions/PassportStepDefs.js
Adding target to support link in footer for accessibility
=> LIME-1037 - Adding target to support link in footer

src/locales/cy/default.yml, src/locales/cy/pages.errors.yml, src/locales/cy/pages.yml, src/locales/en/default.yml, src/locales/en/pages.errors.yml, src/locales/en/pages.yml, test/browser/features/passport/Passport.feature, test/browser/features/passport/WelshPassport.feature, test/browser/pages/PassportPage.js, test/browser/step_definitions/PassportStepDefs.js
References to UK Gov Account team have been updated to UK Gov One Login team.
To align with onboarding to One Login.
- [LIME-718](https://govukverify.atlassian.net/browse/LIME-718)
[LIME-718]: https://govukverify.atlassian.net/browse/LIME-718?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-718 updating Gov UK account to One Login

src/app/passport/fields.js, src/app/passport/fieldsHelper.js, src/app/passport/fieldsHelper.test.js, src/locales/cy/fields.yml, src/locales/en/fields.yml
Removed HMPO maxLength validation for an accessibility requirement. Length validation for all fields are now handled by custom validation in the fieldshelper.js. after form submission
=> LIME-1040 - Removing HMPOComponents max length

test/browser/features/passport/Passport.feature, test/browser/features/passport/WelshPassport.feature, test/browser/pages/PassportPage.js, test/browser/step_definitions/PassportStepDefs.js
Added test steps to support link test to read the updated text in support footer link.
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXX)
=> LIME-1037 Added test steps to support link test to read the updated text in support footer link.

src/app/passport/fields.js, src/app/passport/fieldsHelper.js, src/app/passport/fieldsHelper.test.js, src/locales/cy/fields.yml, src/locales/en/fields.yml
Added custom validation for exact length and removed the use of hmpoComponents exact length for accessibility
=> LIME-1040 - Adding custom exact length validation for passportNumber

deploy/template.yaml
Updated to warn for staging, integration and production.
- [LIME-1127](https://govukverify.atlassian.net/browse/LIME-1127)
[LIME-1127]: https://govukverify.atlassian.net/browse/LIME-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1127 editing env config in template

deploy/template.yaml
Toggle integration and production welsh toggle on
=> DCP-3469: Enabling welsh toggle in passport CRI

deploy/template.yaml
Toggled on GA4 in integration and production
To enable GA4 in production
=> LIME-1173: Enabling GA4 in production and integration

.github/workflows/pre-merge-checks.yml, .pre-commit-config.yaml, .secrets.baseline
- Added pre-commit GHA workflow
-  Updated pre-commit-config with `detect-secrets`
- Added secrets.baseline
- As per ticket requirements
- [IPS-484](https://govukverify.atlassian.net/browse/IPS-484)
[IPS-484]: https://govukverify.atlassian.net/browse/IPS-484?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-487: Add pre-commit GHA workflow and update pre-commit-config

.github/workflows/post-merge-deploy-to-dev.yml, .github/workflows/secure-post-merge.yml
IPS-811 - Updated upload actions ecr version to 1.2.6
- [IPS-811](https://govukverify.atlassian.net/browse/IPS-811)
[IPS-811]: https://govukverify.atlassian.net/browse/IPS-811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-811 - Updated upload actions ecr version to 1.2.6

.pre-commit-config.yaml, .secrets.baseline, deploy/template.yaml
IPS-741 Lime CloudFront Link
Enabled CloudFront Distribution WAF Link in all environments inc Prod
- CloudFront WAF Link is in count mode in prod right now, this enables the actual WAF link in blocking mode in all envs.
updated the pre-commit versions - cfn-lint was very out of date. Updated .secrets.baseline. 
modified:   .pre-commit-config.yaml
modified:   .secrets.baseline
modified:   deploy/template.yaml
- [IPS-741](https://govukverify.atlassian.net/browse/IPS-741)
[IPS-741]: https://govukverify.atlassian.net/browse/IPS-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> IPS-741 Lime CloudFront Link

src/views/errors/error.html, src/views/errors/page-not-found.html, src/views/errors/session-ended.html, src/views/passport/details.html
Taxonomy Level 1 value for all pages updated from "cri" to "web cri" as requested by the Data & Analytics team
As part of the CI changes following GA4 go live
(DFC-640)[https://govukverify.atlassian.net/browse/DFC-640]
=> DFC-640 | GA4| Update taxonomy level1 for pageViewTracker

.secrets.baseline, deploy/template.yaml, package.json, yarn.lock
Upgraded connect-dynamo dependency 
Removed duplication in template.yaml
To fix failing tests in dev and build environment.
- [LIME-1267](https://govukverify.atlassian.net/browse/LIME-1267)
- [IPS-1118](https://govukverify.atlassian.net/browse/IPS-1118)
[LIME-1267]: https://govukverify.atlassian.net/browse/LIME-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[IPS-1118]: https://govukverify.atlassian.net/browse/IPS-1118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1267 upgraded connect-dynamodb

package.json, yarn.lock
Reverts govuk-one-login/ipv-cri-uk-passport-front-v1#178
=> Revert "BAU: Bump hmpo-components from 5.5.2 to 7.1.0"

.secrets.baseline, Dockerfile, deploy/template.yaml
Healthcheck configured and Dockerfile command amended to create unique DYNATRACE_HOST_ID value for different containers. 
The healthcheck ensures fast failure if containers are taking to long to respond. Having unique DYNATRACE_HOST_ID values allows for monitoring of different containers. 
- [LIME-1345](https://govukverify.atlassian.net/browse/LIME-1345)
- [LIME-1351](https://govukverify.atlassian.net/browse/LIME-1351)
Same amendments made to Fraud and DL.
- Successful user journey carried out locally 
- FE unit tests and feature tests passing:
- BE UI Feature tests passing (@stub tests in dev environment):
- Confirmed passport /healthcheck route working:
- Confirmed passport healthcheck task works:
[LIME-1345]: https://govukverify.atlassian.net/browse/LIME-1345?atlOrigin=eyJpIjoiNWRkNTljN …
=> LIME-1345 healthcheck configured

deploy/template.yaml, package.json, src/app-setup.js
Added Frontend Vital Signs Logging for Values insightful to Capacity Management
=> LIME-1343 - Added FE Vital Signs logging

.pre-commit-config.yaml, eslint.config.mjs, package.json, test/browser/step_definitions/PassportStepDefs.js, test/browser/step_definitions/errors.js, test/browser/support/setup.js, yarn.lock
This PR contains a new step in the tests. Upon each page loaded: Fraud Check Page. The Axe Accessibility Script will execute against the 'wcg2aa' (WCGA 2.2 AA) ruleset. And report out any violations as warnings.
- [LIME-1514](https://govukverify.atlassian.net/browse/LIME-1514)
All tests passed locally
[LIME-1514]: https://govukverify.atlassian.net/browse/LIME-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1514: Added Axe Accessibility Script to run on page load

deploy/template.yaml, package.json, src/app.js
- [LIME-XXXX](https://govukverify.atlassian.net/browse/LIME-XXXX)
=> LIME-1512 Common Express updated with cookie banner fix

deploy/template.yaml, yarn.lock
Increase task size so Node has a second CPU per container
To improve event-loop latency/performance
- [LIME-1552](https://govukverify.atlassian.net/browse/LIME-1552)
- [DCP-4451](https://govukverify.atlassian.net/browse/DCP-4451)
[LIME-1552]: https://govukverify.atlassian.net/browse/LIME-1552?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[DCP-4451]: https://govukverify.atlassian.net/browse/DCP-4451?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1552 - Increase task size so Node has a second CPU per container

package.json, test/browser/features/passport/Passport.feature, test/browser/features/passport/WelshPassport.feature, yarn.lock
Update common-express to v10.3.0
To bring in changes made in LIME-1543 for 403 error handling
- [LIME-1578](https://govukverify.atlassian.net/browse/LIME-1578)
[LIME-1578]: https://govukverify.atlassian.net/browse/LIME-1578?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1578 update common-express to v10.3.0

.secrets.baseline, deploy/template.yaml
Make NODE_ENV settings consistent across different environments.
Added NODE_ENV mapping to template.
- [LIME-1604](https://govukverify.atlassian.net/browse/LIME-1604)
[LIME-1604]: https://govukverify.atlassian.net/browse/LIME-1604?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1604 Standardised NODE_ENV configuration for Passport

test/browser/features/passport/Passport.feature, test/browser/features/passport/WelshPassport.feature, test/browser/pages/PassportPage.js, test/browser/pages/UniversalSteps.js, test/browser/step_definitions/PassportStepDefs.js, test/browser/step_definitions/details.js, test/browser/util/TestDataCreator.js
Refactoring of step defs for clarity and to improve reliability of tests. 
- [LIME-1005](https://govukverify.atlassian.net/browse/LIME-1005)
Linked with [LIME-1004](https://govukverify.atlassian.net/browse/LIME-1004) - similar refactoring in Fraud FE
[LIME-1005]: https://govukverify.atlassian.net/browse/LIME-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1005]: https://govukverify.atlassian.net/browse/LIME-1005?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1004]: https://govukverify.atlassian.net/browse/LIME-1004?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1005 Step def refactoring

deploy/template.yaml
Toggle Device Intelligence to true in Staging-Production
To Enable Device Intelligence Staging-Production
- [LIME-1636](https://govukverify.atlassian.net/browse/LIME-1636)
[LIME-1636]: https://govukverify.atlassian.net/browse/LIME-1636?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1636 Enable Device Intelligence Staging-Production

package.json, yarn.lock
Updating @cucumber/cucumber version to 11.3.0.
- [LIME-1799](https://govukverify.atlassian.net/browse/LIME-1799)
[LIME-1799]: https://govukverify.atlassian.net/browse/LIME-1799?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> LIME-1799: Updating @cucumber/cucumber version.
