deploy/template.yaml

FrontGatewayId as required by dns-records
Required in https://github.com/alphagov/di-ipv-cri-common-infrastructure/blob/main/dns-records/template.yaml#L115-L117
- [PLAT-833](https://govukverify.atlassian.net/browse/PLAT-833)
[PLAT-833]: https://govukverify.atlassian.net/browse/PLAT-833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FrontGatewayId as required by dns-records

---

package.json
src/app/passport/controllers/details.test.js
src/app/passport/fieldsHelper.js
src/app/passport/fieldsHelper.test.js
src/lib/config.js

Change the paths 
SESSION from initialise-session to session
AUTHORIZATION from build-client-oauth-response to authorization
Small addition to package.json to allow applying the prettier formatting rules needed to pass lint checks.
Modified/Added tests to bring coverage above 80%.
These paths by convention follow the lambdas names behind the API gateway. These lambdas are now the common-api session and authorization lambdas, with the API gateways updated in https://github.com/alphagov/di-ipv-cri-uk-passport-api/pull/11
Pre-merge was failing due to coverage being under 80%.
Several tests cases for null/zero length fields where added.
In the test "should clear showRetryMessage in session", using a temporary variable in the expect was causing the coverage report for the code being tested to …

LIME-409 Swap passport lambda paths with the common-cri-api paths.

---

package.json
src/locales/cy/default.yml
src/locales/en/default.yml
yarn.lock

Update common-express to v1.0.0
Update dependancies to versions used by common-express v1.0.0
Removed dependancies no longer used (automatic)
common-express v1.0.0 contains a fix for missing localisation text when accepting/rejecting the cookie banner
- [LIME-665](https://govukverify.atlassian.net/browse/LIME-665)
- [LIME-633](https://govukverify.atlassian.net/browse/LIME-633)
- [common-express v1.0.0](https://github.com/alphagov/di-ipv-cri-common-express/releases/tag/v1.0.0)
[LIME-665]: https://govukverify.atlassian.net/browse/LIME-665?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-633]: https://govukverify.atlassian.net/browse/LIME-633?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-633 Fix cookie banner localisation and update common-express to bring in cookie banner localisation fix

---

.github/workflows/checkov.yml
.github/workflows/post-merge-deploy-to-dev.yml
.github/workflows/pre-merge-checks.yml
deploy/template.yaml
sonar-project.properties

Aligned passport-v1 naming terminology with DL/Fraud/CIC templates.
Added front-v1 push into passporta-dev pipeline.
Corrected pre-merge sonar scans not working.
renamed job from run-tests to run-premerge-checks
Set checkov scan to softfail.
Created mappings for min/max containers based on environment.
Passports template was found to be duplicating some of dev-platform deployment steps in the template. 
DL was used as the main reference with existing passport values kept for the container scaling values (see front end auto-scaling  below) and kms logging.
Passport dev pipeline is setup but had no action created to push to the environment.
Sonar action was missing tokens and was pointed at passport-front vs  passport-front-v1.
run-premerge-check is more descriptive.
Checkov scans are kept …

LIME-688 Add front-v1 push into passporta-dev pipeline, correct pre-merge sonar scans not working , align passport-front-v1 template

---

deploy/template.yaml

Set ownership controls on s3 bucket
In order to deploy s3 buckets with ACLs we must set ownernship. Only effects newstacks

LIME-741: Fixing issue where s3 buckets can not be deployed with ACLs

---

deploy/template.yaml

Uncommented the log group subscription filters  
To enable front end logs to be forwarded
- [LIME-802](https://govukverify.atlassian.net/browse/LIME-802)
[LIME-802]: https://govukverify.atlassian.net/browse/LIME-802?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-802 enable log group subscription filters

---

src/app/passport/fieldsHelper.js
src/app/passport/fieldsHelper.test.js

Correcting firstname middlename calculation
Incorrectly allowing 30 characters to pass if sent as first name and middle name
- [LIME-803](https://govukverify.atlassian.net/browse/LIME-803)
[LIME-803]: https://govukverify.atlassian.net/browse/LIME-803?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-803 Correcting firstname middlename bug

---

src/locales/cy/default.yml
src/locales/cy/pages.errors.yml
src/locales/en/default.yml
src/locales/en/pages.errors.yml
test/browser/features/passport/Passport.feature
test/browser/pages/PassportPage.js
test/browser/step_definitions/PassportStepDefs.js

The support link has been changed to the new one-login version.
Due to contact centre being onboarded to one-login.
- [LIME-834](https://govukverify.atlassian.net/browse/LIME-834)
[LIME-834]: https://govukverify.atlassian.net/browse/LIME-834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Lime 834 Updating support link for contact centre one-login

---

deploy/template.yaml
package.json
src/app.js
src/lib/config.js

Added config to set the log level to request and debug in the lower environments
To ensure log levels are always correctly set in the higher environments for hmpo-app and common express

LIME-868: Setting log level to request by default and debug for dev runs

---

src/app/passport/controllers/details.js
src/app/passport/controllers/details.test.js
test/browser/features/passport/Passport.feature

The functionality for dates has been changed so the passport webform will only accept a four digit year value. If someone tries to input two digits, they will be informed they should enter the value as it appears on their passport.
This was changed due to a bug where users were allowed to enter a two digit expiry date but the logic was assuming it was '19' instead of '20' for the century.
- [LIME-784](https://govukverify.atlassian.net/browse/LIME-784)
[LIME-784]: https://govukverify.atlassian.net/browse/LIME-784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-784 DoB and Expiry only accept 4 digits

---

src/app-setup.js
src/app-setup.test.js
src/app.test.js

The helmet.js import for common-express was modified during the GA4 implementation to match how other files were being imported, that modification has been reverted and the tests updated accordingly.
The change to how helmet.js was imported resulted in the CSP errors appearing to be resolved, in reality the config was not being passed into the repository correctly. This PRs change fixes this issue.
- [DFC-529](https://govukverify.atlassian.net/browse/DFC-529)
[DFC-529]: https://govukverify.atlassian.net/browse/DFC-529?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

DFC-529 - Revert helmet.js import change

---

package.json
src/app/passport/controllers/validate.js
yarn.lock

A new version of common-express has been introduced, so we can pass through headers for cloudfront correctly. 
- [LIME-1127](https://govukverify.atlassian.net/browse/LIME-1127)
[LIME-1127]: https://govukverify.atlassian.net/browse/LIME-1127?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1127 changes to headers for cloudfront

---

deploy/template.yaml

IPS-741 Added CloudFront Association to Passport Front Deployment
IPS-741 Added CloudFront Association to Passport Front Deployment
- [IPS-741](https://govukverify.atlassian.net/browse/IPS-741)
[IPS-741]: https://govukverify.atlassian.net/browse/IPS-741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

IPS-741 Added CloudFront Association to Passport Front Deployment

---

.secrets.baseline
deploy/template.yaml

Stage 1 of 2 for enabling ECS Canaries (Stage 2 is [here](https://github.com/govuk-one-login/ipv-cri-uk-passport-front-v1/pull/153))
Added the ECSCanaryDeployment nested Stack to handle Blue/Green ECS deployments
Assumption made that we will always want to have Canary infrastructure in place (even if deployment strategy is AllAtOnce)
Canary deployments provide extra safety measures when rolling out new application image versions
https://govukverify.atlassian.net/browse/IPS-557
AllAtOnce rollout tested in `-dev`:

IPS-557: ecs canary stage 1 - add nested stack

---

.secrets.baseline
deploy/template.yaml

Stage 2 of 2 for enabling ECS Canaries (Stage 1 is [here](https://github.com/govuk-one-login/ipv-cri-uk-passport-front-v1/pull/152))
This is a fairly arbitrary change to trigger the deployment process, but removes some now-unused ECS config.
Canary deployments provide extra safety measures when rolling out new application image versions
https://govukverify.atlassian.net/browse/IPS-557

IPS-557: ecs canary stage 2 - deploy using nested stack

---

package.json
src/app.test.js
src/dynamo-session-config.js
yarn.lock

Upgrade aws-sdk V2 to V3 as AWS SDK for JavaScript v2 entered maintenance mode on September 8, 2024.
Upgraded aws-sdk in package.json to V3.
Dynamo session config and app.test were updated to reflect the V3 format
- [LIME-1267](https://govukverify.atlassian.net/browse/LIME-1267)
[LIME-1267]: https://govukverify.atlassian.net/browse/LIME-1267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[LIME-1267] Upgraded aws-sdk

---

.github/workflows/post-merge-deploy-to-dev.yml
.github/workflows/pre-merge-checks.yml
.github/workflows/secure-post-merge.yml
.pre-commit-config.yaml
.secrets.baseline
deploy/template.yaml

- Add SAM validate on pre-merge checks and lint on the post merge checks
The following changes were required to pass the new linting steps:
1. Add metadata to ignore check `W3045 # Using a legacy 'AccessControl: LogDeliveryWrite'` setup for now
2. Create condition for `HealthCheckGracePeriodSeconds` (this Property is only used if canaries are disabled ie if the service is using a load balancer and not managed by CodeDeploy). This was to fix `E3056 | ECS service using HealthCheckGracePeriodSeconds must also have LoadBalancers specified` [E3056](https://github.com/aws-cloudformation/cfn-lint/blob/main/src/cfnlint/rules/resources/ecs/ServiceHealthCheckGracePeriodSeconds.py) See the docs at:
- https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service_definition_parameters.html
- …

IPS-1118: Bau gha add lint on pre-merge and post-merge checks.

---

package.json

Uglify dependency updated to 3.19.3 from 3.17.4, precipitated by [this Dependabot PR](https://github.com/govuk-one-login/ipv-cri-uk-passport-front-v1/pull/156). This required manual intervention as Dependabot was not updating the package.json setting of the uglify version.  
Successful user journey carried out to manually test this update. FE unit and acceptance tests all passing. BE UI acceptance tests all passing.  
No ticket

LIME-updates uglify dependency

---

package.json
src/locales/cy/fields.yml
src/locales/en/fields.yml

hmpo-components updated to v7.1.0. This was previously a breaking update due to a .prefix box appearing in every input field in the browser. Workaround implemented to resolve this. 
To facilitate update to v7.1.0
- [LIME-1480](https://govukverify.atlassian.net/browse/LIME-1480)
Same update and workarounds being implemented in DL and Fraud FEs.
Evidence on ticket
[LIME-1480]: https://govukverify.atlassian.net/browse/LIME-1480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1480 hmpo-components updated and fix implemented

---

.github/dependabot.yml

Changes made to update dependabot open PR limit to 20 due to present limit of 5 being too few given some PRs can be blocked for some time. 
This FE repo has no dependencies that require grouping so no update made regarding grouping dependencies. 
- [LIME-1229](https://govukverify.atlassian.net/browse/LIME-1229)
[LIME-1229]: https://govukverify.atlassian.net/browse/LIME-1229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1229 updates Dependabot open PR limit

---

src/app-setup.js
src/app-setup.test.js
src/app.js

Add SIGTERM shutdown, and adjust keepalivetimeout duration to longer than loadbalancer timeout
To implement gracefull shutdown and avoid mismatch between loadbalancer timeout and keepalive.
- [LIME-1352](https://govukverify.atlassian.net/browse/LIME-1352)
- https://govukverify.atlassian.net/browse/DCP-4450
- https://github.com/govuk-one-login/ipv-cri-address-front/pull/1084
- https://github.com/govuk-one-login/ipv-cri-common-express/pull/474
[LIME-1352]: https://govukverify.atlassian.net/browse/LIME-1352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1352 Add SIGTERM shutdown, and adjust keepalivetimeout duration to longer than loadbalancer timeout (DCP-4450)

---

.secrets.baseline
deploy/template.yaml

This is protected by a specific WAF for CloudFront
Added tags to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
Added tags
to exclude the origin load balancer from FMS as it has it's own CloudFront specific WAF
https://govukverify.atlassian.net/browse/IPS-1407

Update to  exclude the origin load balancer from the regional FMS policy

---

package.json

Upgrading FE Vital signs to log max EventLoopDelay (fix brought in by latest patch version)

LIME-1546 Upgrading FE Vital signs to log max EventLoopDelay

---

src/locales/en/default.yml

The aria-label for the language toggle when /check page is in English should also be in English so that English speaking screenreader users receive instructions in a language they understand.
Updated aria-label in english locale file
- [LIME-1510](https://govukverify.atlassian.net/browse/LIME-1510)
[LIME-1510]: https://govukverify.atlassian.net/browse/LIME-1510?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1510 Language Toggle: Updated aria-label 

---

.github/workflows/pre-merge-checks.yml

Bumped the GH Action to use the new SonarCloud GH Action
Upstream action deprecated
https://govukverify.atlassian.net/browse/IPS-1428

IPS-1428 update sonarcloud version before march deadline

---

src/locales/cy/default.yml
src/locales/en/default.yml
test/browser/features/passport/Passport.feature
test/browser/features/passport/WelshPassport.feature

serviceName amended to remove _"... - Prove your identity" from page tab titles in DL FE. FE tests updated to reflect this and the adding of 'One Login' to the pageTitle suffix brought in by the Common Express update.
To keep this service in line with other services of the programme and fix failing tests as a result of the Common Express update beyond 10.1.x.
- [LIME-1591](https://govukverify.atlassian.net/browse/LIME-1591)
[LIME-1508]: https://govukverify.atlassian.net/browse/LIME-1508?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[LIME-1591]: https://govukverify.atlassian.net/browse/LIME-1591?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1591 - pageTitle updated in line with One Login programme

---

.github/workflows/pre-merge-checks.yml
.husky/pre-commit
.husky/pre-push
package.json
test/browser/features/passport/Passport.feature
test/browser/pages/PassportPage.js
test/browser/step_definitions/PassportStepDefs.js
yarn.lock

Added new AC Test to check for device Intelligence cookie and that it has a value
New AC Test Added to fraud.feature
Removed Husky Folder as no longer used
To check that the new device intelligence cookie has been loaded correctly after Fraud Check Page load
- [LIME-1641](https://govukverify.atlassian.net/browse/LIME-1641)
[LIME-1641]: https://govukverify.atlassian.net/browse/LIME-1641?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1641 Add Device Intelligence AC Tests to check for Cookie

---

package.json
test/browser/features/passport/Passport.feature
test/browser/pages/relying-party.js
test/browser/step_definitions/relying-party.js
test/mocks/mappings/passport-check-error.json
test/mocks/mappings/passport-fail.json
test/mocks/mappings/passport-slow.json
test/mocks/mappings/passport.json
yarn.lock

Yarn.lock removed and re-created to pull in changes from transitive dependency frontend-ui through common-express.  
To bring in the fix to increase the footer font size to 16px.
- [LIME-1770](https://govukverify.atlassian.net/browse/LIME-1770)
[LIME-1770]: https://govukverify.atlassian.net/browse/LIME-1770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1770 - yarn.lock updated to pull in frontend-ui update

---

package.json
yarn.lock

Upgrade Axios and Waiton
Resolve transitive dependency issues
- [LIME-1775](https://govukverify.atlassian.net/browse/LIME-1775)
[LIME-1775]: https://govukverify.atlassian.net/browse/LIME-1775?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

LIME-1775 Upgrade axios and waiton
